### PR TITLE
Add invert_permutation and invert_permutation_unchecked

### PR DESCRIPTION
**Pull request by progval**

### CODE REVIEW

**Comment by progval** [comment]
I didn't implement an in-place variant because this is most likely going to be generated from the iterator in #36

**Comment by vigna** [comment]
Well webgraph is not really the right place tho. I guess we can leave this around until we find a better home...

**Comment by progval** [comment]
no problem, I don't mind having it in swh-graph's crate

**Comment by progval** [comment]
In the end I don't even need it in swh-graph because I implemented the order generation differently, and as a side-effect it gives me the permutation directly

**Pull request closed without merging**
